Project 1: Setup and mobile version skeleton
Kambuchi/Portfolio pull request #1
Opened 2021-08-09 22:04 UTC by Kambuchi

- Basic files created
- Hero: content and style added
- Images: icons added

2021-08-10 17:24 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @Kambuchi , You did a great job so far 👏🏼 👏🏼 

- The repository looks professional.
- You did well in implementing the project specifications and following the Figma design. 

However, here are some points that you need to work on to get your project approved.

## Required changes :

- [ ] Check the inline comments.

- [ ]  Kindly check this [link](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) about how to write meaningful commit messages

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-10 17:24 UTC, safafa commented on style.css
> +}
- [ ] To better follow the DRY concept you can refactor the code by grouping repeated CSS code into a separate class.  for example : 
`.flex {
display: flex;
}`

- [ ] [OPTIONAL] Check this [link](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_propertiesl) about setting CSS variables if you want to make your code better.

2021-08-10 17:24 UTC, safafa commented on index.html
> +                <li><img src="./img/ic_angellist.svg" alt="angellist profile"></li>
- [ ] All the icons are clickable. Kindly use the correct HTML tag. As a suggestion, you can use a or button tag.

2021-08-11 16:59 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Kambuchi Pereira Montañez, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-11 17:04 UTC, merged