Create work section's html structure
Kambuchi/Portfolio pull request #2
Opened 2021-08-11 22:59 UTC by Kambuchi

2021-08-12 18:22 UTC, addod19 requested changes
### Hi @Kambuchi , 

Good job so far! Git flow followed :muscle: PR and commit messages very professional :fireworks:
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

__Happy coding__ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-08-12 18:22 UTC, addod19 commented on index.html
> +            <section class="about">
- [ ] It would be better if we implement the `border-top-right-radius` feature to have the effect in the design

2021-08-12 18:22 UTC, addod19 commented on index.html
> +                <span class="lets-connect">LET'S CONNECT</span>
- [ ] It would be better if we change the `<span class="lets-connect">` to `<hx class="lets-connect">`

2021-08-12 18:22 UTC, addod19 commented on index.html
> +                <div class="knowledge">
- [ ] It would be better if we change the `<div class="knowledge">` to `<ul class="knowledge">`. It is better to improve HTML semantics by using the `<ul>` for listings

2021-08-12 18:22 UTC, addod19 commented on index.html
> +                    <h3>Languages<a href="#">></a></h3>
- [ ] It would be better if we change the `<h3>` to `<li>`. It is better to improve HTML semantics by using the `<li>` for listings

2021-08-12 18:22 UTC, addod19 commented on style.css
> +  margin-bottom: 20px;
- [ ] It would be better if we implement the CSS DRY principle. We have a few repeating rules which we have to fix. This can be achieved in this way:
```
.class1, .class2 {
  margin-bottom: 20px;
}
```

2021-08-12 18:22 UTC, addod19 commented on index.html
>  <!DOCTYPE html>
- [ ] It would be better if we include the instructions about how to clone and run the project locally in the README file, so that non-technical people can also interact with the application

2021-08-13 21:00 UTC, AshakaE approved these changes
### Hi @Kambuchi  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the required changes 👍 
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] 
consider using `cursor: pointer;` for when a button is hovered 💡 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 21:18 UTC, merged